#!/usr/bin/env bash
#
# Licencia: GPL-3.0-or-later
#
# apply-kernel-patches.sh
#
# Aplica los parches downstream de patches/kernel/ sobre un árbol de kernel
# mainline v7.1, verificando que cada uno aplique limpio con git apply.
#
# Parches:
#   0001-dts-mdss-panel-s6e8fc0.patch  Enable MDSS + panel S6E8FC0 (typo corregido)
#   0002-dtsi-gpu-adreno610.patch      Nodos GPU (gpu/gmu_wrapper/gpucc/adreno_smmu)
#   0003-dts-enable-gpu.patch          Enable GPU + zap-shader en DTS de placa
#   0004-dts-enable-wifi-wcn3990.patch Nodo WCN3990 SNOC + MSA/reguladores
#
# Uso:
#   scripts/apply-kernel-patches.sh <árbol-kernel>

set -Eeuo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

TREE="${1:-}"
if [[ -z "$TREE" ]]; then
  echo "uso: $0 <árbol-kernel>" >&2
  exit 2
fi
[[ -d "$TREE" ]] || { echo "ERROR: árbol no existe: $TREE" >&2; exit 1; }

PATCH_DIR="$REPO_ROOT/patches/kernel"
shopt -s nullglob
PATCHES=("$PATCH_DIR"/*.patch)

if (( ${#PATCHES[@]} == 0 )); then
  echo "Sin parches en $PATCH_DIR"
  exit 0
fi

cd "$TREE"

PATCH_COUNT=0
for p in "${PATCHES[@]}"; do
  git apply --check "$p" || {
    echo "ERROR: $p no aplica limpio sobre $TREE" >&2
    echo "  ejecuta: git apply --verbose '$p' para diagnóstico" >&2
    exit 1
  }
  git apply "$p"
  PATCH_COUNT=$((PATCH_COUNT + 1))
  echo "aplicado: $(basename "$p")"
done

# Commit the applied patches so git state is clean (avoids -dirty in kernelrelease).
# The commit message is deterministic and includes the patch list.
COMMIT_MSG="downstream: apply $(basename "$PATCH_DIR") patch stack

Patches applied in order:"
for p in "${PATCHES[@]}"; do
  COMMIT_MSG="$COMMIT_MSG
  - $(basename "$p")"
done
COMMIT_MSG="$COMMIT_MSG

Generated by scripts/apply-kernel-patches.sh"

git add -A
git commit -m "$COMMIT_MSG" --quiet

echo "OK: ${#PATCHES[@]} patches applied and committed (tree is clean)"
echo "HEAD: $(git rev-parse HEAD)"
echo "describe: $(git describe --always 2>/dev/null || git rev-parse --short HEAD)"
